name: Deploy via SSH

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to VPS and pull latest code
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_KEY }}
          script: |
            cd kam-bot
            git pull origin main
            ./scripts.sh restart
